language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t iuriimudrak/docker-react -f Dockerfile.dev .

script: docker run -e CI=true iuriimudrak/docker-react npm run test
